#! /usr/bin/python

import os

# We get the desired folder path
folder = r"C:\Users\Public"

# We store the contents of the folder in a variable
folder_contents = os.listdir(folder)
folder_length = len(folder_contents)
# Iterate through the folder contents and create a new list of only files we'll change
nameChangeList = []
def findFiles():
    for item in range(folder_length):
        item = folder_contents[item]
        file_path = os.path.join(folder,item)
        fileName, fileExtension = os.path.splitext(file_path)
        if fileExtension == '.txt':
            print item
            try:
                float(item[:2])
                print True
            except ValueError:
                print False
        #print fileExtension
    
    print nameChangeList

def nameChange(file):
    newName = ""
    folderPath = ''
    
    os.rename(r"%s",r"%s") % (file,newName)
    
findFiles()
#os.rename(r"C:\Users\Public\testdoc.txt", r"C:\Users\Public\easyAsPython.txt")

