#! /usr/bin/python

# Allowing Python to access folders in your OS
import timing
import os, sys
from stat import *

# We get the desired folder path
folder = r"C:\Users\Public\Mynewfolder"

# We store the contents of the folder in a variable
folder_contents = os.listdir(folder)
folder_length = len(folder_contents)

# Iterate through the folder contents and create a new list of only files we'll change
# Or...Iterate through list while making changes in real-time


def changeName(pathname):
    head, tail = os.path.split(pathname)
    try:
        float(tail[:3])
        newName = tail[3:]
        newCompleteName = os.path.join(head,newName)
        os.rename(pathname, newCompleteName)
    except ValueError:
        print False

def findFiles(top, callback):
    for item in os.listdir(top):
        pathname = os.path.join(top, item)
        fileName, fileExtension = os.path.splitext(pathname)
        mode = os.stat(pathname)[ST_MODE]
        if S_ISDIR(mode):
            # It's a directory, recurse into it
            print pathname, "This is a directory"
            findFiles(pathname, callback)
        elif S_ISREG(mode):
            # It's a file, call the callback function
            print pathname, "This is a file"
            if fileExtension == '.txt':
                callback(pathname)
        else:
            # Unknown file type, print a message
            print 'Skipping %s' % pathname

#def nameChange(pathname):

def walktree(top, callback):
    '''recursively descend the directory tree rooted at top,
       calling the callback function for each regular file'''

    for f in os.listdir(top):
        pathname = os.path.join(top, f)
        mode = os.stat(pathname)[ST_MODE]
        if S_ISDIR(mode):
            # It's a directory, recurse into it
            walktree(pathname, callback)
        elif S_ISREG(mode):
            # It's a file, call the callback function
            callback(pathname)
        else:
            # Unknown file type, print a message
            print 'Skipping %s' % pathname
    
    
#findFiles()
findFiles(folder, changeName)
#os.rename(r"C:\Users\Public\testdoc.txt", r"C:\Users\Public\easyAsPython.txt")
